[build]
  publish = "build/"
  command = "docusaurus build"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_YARN = false
  PNPM_FLAGS = "--frozen-lockfile"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
