export default {
  'comment': /\$c\[[\s\S]*?\]/,
  'bds-escape': /(?:\\[\\\];]|%(?:ESCAPED|{(?:DOL|-SEMICOL-)})%)/,
  'bds-punctuation': /[\[\;\]]/,
  'bds-callback': [
    /\$awaitedCommand(?:Error)?/,
    /\$on(?:Joined|Leave|AutoComplete|BanAdd|BanRemove|MessageDelete|Interaction)/
  ],
  'bds-premium-callback': /\$(?:alwaysReply|messageContains|reaction)/,
  'bds-premium-function': /\$(?:awaitReactions|customImage|sendNotification|usedEmoji|ignoreTriggerCase)/,
  'bds-deprecated': /\$(?:modifyChannelPerms|channelIDFromName|giveRole|takeRole|unmute|mute|userJoinedDiscord)/,
  'bds-http': /\$http(?:AddHeader|RemoveHeader|GetHeader|Get|Post|Put|Patch|Delete|Result|Status)/,
  'bds-misc': /\$(?:optOff|tts|changeCooldownTime|alternativeParsing|disableSpecialEscaping|stop|awaitFunc|scriptLanguage|unescape|ignoreLinks|trimContent|disableInnerSpaceRemoval)/,
  'bds-user': /\$(?:user(?:ServerAvatar|Avatar|Info|Perms|Roles)|authorAvatar|discriminator|get(?:User|Custom)Status|username|nickname|hypesquad|changeUsername(?:WithID)?)/,
  'bds-id': /\$(?:authorID|authorOfMessage|botOwnerID|categoryID|channelID|dmChannelID|guildID|messageID|repliedMessageID|parentID|roleID|slashID|userID|findChannel|findUser|findRole|highestRoleWithPerms|highestRole|lowestRoleWithPerms|lowestRole|mentionedChannels|mentionedRoles|mentioned|serverOwner)/,
  'bds-if': /\$(?:if|elseif|else|endif)/,
  'bds-async': /\$(?:async|endasync|await)/,
  'bds-try': /\$(?:try|catch|error|endtry)/,
  'bds-role': /\$(?:(?:color|create|delete)Role|getRoleColor|modifyRole(?:Perms)?|role(?:Grant|Info|Name(?:s)?|Position))/,
  'bds-embed': /\$(?:authorIcon|authorURL|author|description|image|color|thumbnail|title|addField|addTimestamp|embeddedURL|footerIcon|footer)/,
  'bds-webhook': /\$webhook(?:AvatarURL|Create|Color|Content|Delete|Description|Footer|Send|Title|Username)/,
  'bds-timeout': /\$(?:un)?timeout/,
  'bds-time': /\$(?:day|date|getCooldown|getTimestamp|uptime|time|executionTime|hostingExpireTime|premiumExpireTime|creationDate|minute|second|hour|month|ping|year|userJoined)/,
  'bds-math': /\$(?:sort|su[mb]|max|min|enableDecimals|divide|multi|modulo|calculate|round|numberSeparator)/,
  'bds-json': /\$json(?:ArrayAppend|ArrayCount|Array|Clear|Exists|Parse|Pretty|Set|Stringify|Unset)?/,
  'bds-limiter': [
    /\$only(?:IfMessageContains|If|BotChannelPerms|BotPerms|Perms|Admin|NSFW|ForRoleIDs|ForRoles|ForIDs|ForCategories|ForServers|ForUsers|ForChannels)/,
    /\$(?:serverCooldown|globalCooldown|cooldown|ignoreChannels|varExistError|argsCheck|blackList(?:RolesIDs|Roles|IDs|Servers|Users)|enabled)/
  ],
  'bds-component': /\$(?:addButton|editButton|removeButtons|addSelectMenuOption|editSelectMenuOption|newSelectMenu|editSelectMenu|newModal|addTextInput|input|removeComponent|defer|customID|ephemeral)/,
  'bds-str-manip': /\$(?:getTextSplitLength|getTextSplitIndex|joinSplitText|editSplitText|removeSplitTextElement|splitText|textSplit|replaceText|cropText|repeatMessage|trimSpace|toUppercase|toLowercase|toTitleCase)/,
  'bds-boolean': [
    /\$is(?:Admin|Banned|Bot|Boolean|Hoisted|Mentionable|NSFW|Number|Slash|TimedOut|UserDMEnabled|ValidHex)/,
    /\$(?:channelExists|serverChannelExists|guildExists|roleExists|userExists|varExists|userReacted|or|and|hasRole|checkContains|checkCondition|checkUserPerms)/,
  ],
  'bds-random': /\$random(?:ChannelID|Mention|String|Text|UserID|User)?/,
  'bds-bdl': /\$botList(?:Description|Hide)/,
  'bds-nomention': /\$nomention/,
  'bds-reaction': /\$(?:add(?:Cmd)?|clear|get)Reactions/,
  'bds-count': /\$(?:slashCommands|commands|allMembers|members|channel|boost|variables|server|role|emote|char|category|arg)Count/,
  'bds-bot': /\$(?:botID|botLeave|botNode|botCommands|getBotInvite|shardID)/,
  'bds-leaderboard': /\$(?:(?:globalUser|server|user)Leaderboard|getLeaderboardValue)/,
  'bds-slash': /\$(?:appendOptionSuggestion|(?:un)?registerGuildCommands|autoCompleteOption(?:Name|Value))/,
  'bds-ban': /\$(?:(?:un)?ban(?:ID)?|getBanReason)/,
  'bds-kick': /\$kick(?:Mention)?/,
  'bds-server': /\$(?:server(?:Description|Emojis|Icon|Info|Name(?:s)?|Region|VerificationLvl)|getServerInvite)/,
  'bds-channel': /\$(?:channel(?:Name|Type|Position|Topic)|(?:create|use|modify)Channel|deleteChannels(?:ByName)?|editChannelPerms)/,
  'bds-emoji': /\$(?:custom|add)Emoji/,
  'bds-ticket': /\$(?:new|close)Ticket/,
  'bds-error': /\$(?:embedSuppressErrors|suppressErrors)/,
  'bds-thread': /\$(?:startThread|editThread|threadAddMember|threadRemoveMember)/,
  'bds-eval': /\$eval/,
  'bds-message': [
    /\$(?:(?:noMention|edit|get|unpin|pin|publish|send(?:Embed)?|delete|channelSend)M|m)essage/,
    /\$(?:editEmbed|edit|delete|reply)In/,
    /\$(?:allow(?:Mention|UserMentions|RoleMentions)|botTyping|reply)/
  ],
  'bds-util': /\$(?:clear|deletecommand|dm|getEmbedData|getInviteInfo|removeContains|removeLinks|slowmode|url)/,
  'bds-variable': [
    /\$(?:[sg]|res)et(?:Channel|Server|User)Var/,
    /\$(?:[sg]etVar|var)/
  ],
};