name: Docs Deploy
on:
  push:
     branches:
        - main

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    env:
       USER: ${{ github.event.head_commit.author.username }}
       TOKEN: ${{ secrets.GIT_PASS }}
    steps:
       - name: Checkout Repository
         uses: actions/checkout@v3
       - name: Setup Node
         uses: actions/setup-node@v3.5.1
         with:
            node-version: 18
       - name: Install Packages
         run: yarn
       - name: Deploy to GitHub Pages
         run: GIT_USER="$USER" yarn deploy
