name: Docs

on:
  push:
    branches:
         - prod
         - dev

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
       GIT_USER: $GITHUB_ACTOR
       GIT_PASS: ${{ secrets.TOKEN }}
       DEPLOYMENT-BRANCH: 'gh-pages'
       TYPE: 'Production'

    steps:
       - name: Configuration
         run: |
            if [ -z $GIT_PASS ]
            then
                  echo "::error title=Missing secret!::Failed to get TOKEN environment secret!"
                  exit 1
            else
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

                  echo "ORGANIZATION_NAME=${GITHUB_REPOSITORY%/*}" >> $GITHUB_ENV
                  echo "PROJECT_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
            fi

       - name: Checkout Repository
         uses: actions/checkout@v3

       - name: Install Packages
         run: yarn --frozen-lockfile

       - name: Production Deploy
         if: github.ref == 'refs/heads/prod'
         run: yarn deploy

       - name: Development Deploy
         if: github.ref == 'refs/heads/dev'
         run: |
            echo "TYPE=Development" >> $GITHUB_ENV

       - name: Job Summary
         run: |
            echo "Type: ${{ env.TYPE }}" >> $GITHUB_STEP_SUMMARY
            echo "Preview: https://${{ env.ORGANIZATION_NAME }}.github.io/${{ env.PROJECT_NAME }}" >> $GITHUB_STEP_SUMMARY
