name: Docs

on:
  push:
    branches:
         - prod
         - dev

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
       - name: Checkout Repository
         uses: actions/checkout@v3.2.0

       - name: Setup Node
         uses: actions/setup-node@v3.5.1
         with:
             node-version : 18
             cache: 'yarn'

       - name: Install Dependencies
         run: yarn --frozen-lockfile --prefer-offline

       - name: Documentation Build
         run: yarn build

       - name: Deploy to GitHub Pages
         env:
              TOKEN: ${{ github.token }}
         run: sh ./.github/scripts/deploy.sh
