name: Docs

on:
  push:
    branches: [prod, dev]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
       GIT_USER: $GITHUB_ACTOR
       GIT_PASS: ${{ secrets.TOKEN }}
       GIT_REPO: ${{ github.repository }}
    steps:
       - name: Validating Environment Secret
         if: env.GIT_PASS == ''
         run: |
            echo "::error title=Missing secret!::Failed to get TOKEN environment secret!"
            exit 1

       - name: Checkout Repository
         uses: actions/checkout@v3

       - name: Setup Node
         uses: actions/setup-node@v3.5.1
         with:
            node-version: 18
            cache: 'yarn'

       - name: Install Packages
         run: yarn --frozen-lockfile

       - name: Git Configuration
         run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

       - name: Production Deploy
         if: github.ref == 'refs/heads/prod'
         run: |
            yarn deploy
            echo "type=Production" >> $GITHUB_ENV

       - name: Development Deploy
         if: github.ref == 'refs/heads/dev'
         run: |
            echo "type=Development" >> $GITHUB_ENV

       - name: Job Summary
         run: |
            echo "### 🚀 Successfully Deployed! 🚀" >> $GITHUB_STEP_SUMMARY
            echo "Type: ${{ env.type }}" >> $GITHUB_STEP_SUMMARY
            echo "Preview: https://${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
