name: Docs

on:
  push:
    branches: [prod, dev]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
       GIT_USER: $GITHUB_ACTOR
       GIT_PASS: ${{ secrets.TOKEN }}
       DEPLOYMENT-BRANCH: 'gh-pages'
       TYPE: 'Production'

    steps:
       - name: Validate Environment Secret
         run: |
            if [ -z $GIT_PASS ]
            then
               echo "::error title=Missing secret!::Failed to get TOKEN environment secret!"
               exit 1
            fi

       - name: Checkout Repository
         uses: actions/checkout@v3

       - name: Setup Node
         uses: actions/setup-node@v3.5.1
         with:
            node-version: 18
            cache: 'yarn'

       - name: Install Packages
         run: yarn --frozen-lockfile

       - name: Configuration
         run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            echo "ORGANIZATION_NAME=${GITHUB_REPOSITORY%/*}" >> $GITHUB_ENV
            echo "PROJECT_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

       - name: Production Deploy
         if: github.ref == 'refs/heads/prod'
         run: yarn deploy

       - name: Development Deploy
         if: github.ref == 'refs/heads/dev'
         run: |
            echo "TYPE=Development" >> $GITHUB_ENV

       - name: Job Summary
         run: |
            echo "Type: ${{ env.TYPE }}" >> $GITHUB_STEP_SUMMARY
            echo "Preview: https://${{ env.ORGANIZATION_NAME }}.github.io/${{ env.PROJECT_NAME }}" >> $GITHUB_STEP_SUMMARY
