name: Docusaurus
on:
  push:
    branches:
       - prod
       - dev

jobs:
  validate:
    name: Validate Environment Secrets
    runs-on: ubuntu-latest
    env:
        token: ${{ secrets.TOKEN }}
    steps:
       - name: TOKEN
         if: env.token == ''
         run: |
            echo "::error title=Missing secret!::Failed to get TOKEN environment secret!"
            exit 1

  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: validate
    env:
       GIT_USER: $GITHUB_ACTOR
       GIT_PASS: ${{ secrets.TOKEN }}
       PROJECT_NAME: '${GITHUB_REPOSITORY#*/}'
       ORGANIZATION_NAME: '${GITHUB_REPOSITORY%/*}'
       DEPLOYMENT_BRANCH: 'gh-pages'
    steps:
       - name: Checkout Repository
         uses: actions/checkout@v3
       - name: Setup Node
         uses: actions/setup-node@v3.5.1
         with:
            node-version: 18
            cache: 'yarn'
       - name: Install Packages
         run: yarn --frozen-lockfile
       - name: Deploy to GitHub Pages
         run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            yarn deploy
