name: Docusaurus
on:
  push:
    branches:
       - prod
    paths-ignore:
       - '.github/**'

jobs:
  validate:
    name: Validate ENVs
    runs-on: ubuntu-latest
    outputs:
        git_pass: ${{ steps.git_pass.outputs.valid }}
    steps:
       - name: GIT_PASS
          id: git_pass
          env:
             valid: ${{ secrets.GIT_PASS }}
          if: env.valid  != ''
          run: echo "::set-output name=valid::true"

  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [validate]
    if: needs.validate.outputs.git_pass == 'true'
    env:
       GIT_USER: $GITHUB_ACTOR
       GIT_PASS: ${{ secrets.GIT_PASS }}
    steps:
       - name: Checkout Repository
         uses: actions/checkout@v3
       - name: Setup Node
         uses: actions/setup-node@v3.5.1
         with:
            node-version: 18
            cache: 'yarn'
       - name: Install Packages
         run: yarn --frozen-lockfile
       - name: Deploy to GitHub Pages
         run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            yarn deploy
